version: '1.0'

services:
  api:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    networks:
      - hamsai_network
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./hamsai_redis:/data
    networks:
      - hamsai_network
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./hamsai_mongo:/data/db
    networks:
      - hamsai_network

networks:
  hamsai_network:
    driver: bridge
volumes:
  redis_volume: {}
  mongo_volume: {}